name=ESPCar
version=1.0.0
author=Abdul Rafeul Mallick
maintainer=Abdul Rafeul Mallick
sentence=ESP32 robot car control library
paragraph=Arduino library for controlling ESP32 based robot cars over Bluetooth and WiFi.
category=Device Control
url=https://github.com/Rafeul1997/ESPCar
architectures=esp32,esp8266