name=ESP-CAR
version=1.0.0
author=Abdul Rafeul Mallick
maintainer=Abdul Rafeul Mallick
sentence=ESP32 Car control library using Bluetooth and WiFi
paragraph=Control robot car using Bluetooth or WiFi with simple commands and speed control support.
category=Device Control
url=https://github.com/Rafeul1997/ESP-CAR
architectures=esp32
